### ISSUE TITLE
Undefined "translator" dependency in services.yaml

### ISSUE THREAD

**Issue by matejrokos** [mhujer/consistence-bundle#3]
'@translator' in services.yaml is undefined. Installation ends with:

`The service "mhujer_consistence.twig.enum_translator_runtime" has a dependency on a non-existent service "translator". `

**Comment by matejrokos** [comment]
Solved by `composer require symfony/translation` before installing consistence-bundle.

**Comment by matejrokos** [comment]
Occurs when starting project with minimalistic symfony skeleton:
```
composer create-project symfony/skeleton my_project_name
```

Then composer.json requires only these:
```
    "require": {
        "php": "^7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "symfony/console": "5.0.*",
        "symfony/dotenv": "5.0.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "5.0.*",
        "symfony/yaml": "5.0.*"
    },
```
Resp. their v 4.4.1 equivalents in last working consistence-doctrine-symfony version.

**Comment by mhujer** [comment]
@matejrokos fixed, thanks!
